In [20]:
import torch
from transformers import AutoTokenizer, AutoModel

In [21]:
model_name = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')

In [22]:
#tokens = tokenizer.convert_tokens_to_ids(['hello', 'world', 'watch', 'you', 'it'])
#tokens[:-1][:200]
clss = torch.Tensor([0, 7, 13, 12, 0, 0, 0, 0])
mask_cls = 1 - (clss == -1).float()
clss[clss == -1] = 0


In [23]:
inputs = tokenizer(
    [
        'One of the other reviewers has mentioned that after watching just 1 Oz episode you\'ll be hooked. They are right, as this is exactly what happened with me.',
        'One of the other reviewers has mentioned that after watching just 1 Oz episode you\'ll be hooked. They are right, as this is exactly what happened with me.',
    ],
    padding='max_length',
    truncation=True,
    max_length=256,
    return_tensors='pt')
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [27]:
sz = 5
mask = (torch.triu(torch.ones(sz, sz)) == 1).transpose(0, 1)
mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
mask

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [ ]:
[ inputs[key].shape for key in inputs.keys() ]

In [26]:
inputs = {
    'input_ids': inputs['input_ids'],
    'token_type_ids': inputs['token_type_ids'],
    'attention_mask': inputs['attention_mask']
}


In [25]:
inputs['attention_mask']

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 

In [32]:
outputs = model(inputs['input_ids'], attention_mask=inputs['attention_mask'], token_type_ids=inputs['token_type_ids'])
outputs

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.5125, -0.1788, -0.0079,  ..., -0.1353,  0.5351,  0.2676],
         [-0.2296, -0.3768, -0.0012,  ...,  0.1479,  0.9710,  0.0250],
         [-0.3032, -0.5108, -0.0544,  ...,  0.1601,  0.9350, -0.0422],
         ...,
         [-0.2489, -0.2755,  0.2945,  ...,  0.2169,  0.0397,  0.0919],
         [-0.1543, -0.4060,  0.1806,  ...,  0.1462,  0.3092, -0.0734],
         [ 0.0426, -0.5663,  0.4506,  ...,  0.3674, -0.2194, -0.0276]],

        [[ 0.5125, -0.1788, -0.0079,  ..., -0.1353,  0.5351,  0.2676],
         [-0.2296, -0.3768, -0.0012,  ...,  0.1479,  0.9710,  0.0250],
         [-0.3032, -0.5108, -0.0544,  ...,  0.1601,  0.9350, -0.0422],
         ...,
         [-0.2489, -0.2755,  0.2945,  ...,  0.2169,  0.0397,  0.0919],
         [-0.1543, -0.4060,  0.1806,  ...,  0.1462,  0.3092, -0.0734],
         [ 0.0426, -0.5663,  0.4506,  ...,  0.3674, -0.2194, -0.0276]]],
       grad_fn=<NativeLayerNormBackward>), pooler_out

In [50]:
inputs['input_ids'].dtype, inputs['attention_mask'].dtype, inputs['token_type_ids'].dtype



(torch.int64, torch.int64, torch.int64)

In [ ]:
cls = torch.Tensor([3, 10])
top_vec = outputs.last_hidden_state
top_vec[torch.arange(top_vec.size(0)).unsqueeze(1), [13, 26, 39]].shape

In [41]:
torch.arange(top_vec.size(0)).unsqueeze(1).shape

torch.Size([2, 1])

In [42]:
top_vec.shape

torch.Size([2, 256, 768])

In [9]:
cls_ids = [[0, 14, 26, 32, 41, 50, 56]]
clss = torch.tensor(cls_ids)
mask_cls = 1 - (clss == -1).float()
mask_cls

tensor([[1., 1., 1., 1., 1., 1., 1.]])

In [10]:
clss[clss == -1] = 0
clss

tensor([[ 0, 14, 26, 32, 41, 50, 56]])

In [18]:
a = torch.Tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b = torch.Tensor([[[1, 1, 0], [1, 0, 0]], [[1, 1, 1], [1, 0, 0]]])

In [19]:
a * b

tensor([[[ 1.,  2.,  0.],
         [ 4.,  0.,  0.]],

        [[ 7.,  8.,  9.],
         [10.,  0.,  0.]]])